"""user_centric

Revision ID: ba4f1295473c
Revises: 001_initial
Create Date: 2026-04-23 06:36:32.695160
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ba4f1295473c'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.add_column('assets', sa.Column('allowed_use_notes', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index('ix_cases_owner', 'cases', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'cases', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_index('ix_cases_owner', table_name='cases')
    op.drop_column('cases', 'owner_id')
    op.drop_column('assets', 'allowed_use_notes')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
